const path = require('path');

const ROOT = process.env.PAYESH_ROOT || __dirname;
const LOG_DIR = path.join(ROOT, 'logs');
const PROCESS_POLICY = {
  exp_backoff_restart_delay: 100,
  listen_timeout: 10000,
  kill_timeout: 5000,
};

module.exports = {
  apps: [
    {
      name: 'hoshmak-back',
      cwd: path.join(ROOT, 'hoshmak-back'),
      script: 'dist/main.js',
      env: {
        NODE_ENV: 'development',
        CAPTCHA_URL: 'http://127.0.0.1:8088',
        PASSWORD_RESET_VIA_EMAIL: 'true',
        SOURCE_ONBOARDING_QUEUE_ENABLED: '1',
        CRAWL_CALLBACK_SECRET: process.env.CRAWL_CALLBACK_SECRET,
        // Load email secrets from deploy/hoshmak-resend.env on the server (see payesh-deploy repo)
        EMAIL_PROVIDER: 'resend',
      },
      error_file: path.join(LOG_DIR, 'hoshmak-back-error.log'),
      out_file: path.join(LOG_DIR, 'hoshmak-back-out.log'),
      merge_logs: true,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      ...PROCESS_POLICY,
    },
    {
      name: 'hoshmak-front',
      cwd: path.join(ROOT, 'hoshmak-front'),
      script: 'node_modules/vite/bin/vite.js',
      args: 'preview --host 0.0.0.0 --port 4000 --strictPort',
      env: {
        NODE_ENV: 'production',
      },
      error_file: path.join(LOG_DIR, 'hoshmak-front-error.log'),
      out_file: path.join(LOG_DIR, 'hoshmak-front-out.log'),
      merge_logs: true,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      ...PROCESS_POLICY,
    },
    {
      name: 'ai-services',
      cwd: path.join(ROOT, 'ai-services'),
      script: 'dist/main.js',
      env: {
        NODE_ENV: 'development',
        DB_HOST: 'localhost',
      },
      error_file: path.join(LOG_DIR, 'ai-services-error.log'),
      out_file: path.join(LOG_DIR, 'ai-services-out.log'),
      merge_logs: true,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      ...PROCESS_POLICY,
    },
    {
      name: 'flaresolverr',
      cwd: path.join(ROOT, 'content-production'),
      script: 'docker',
      args: 'compose -f docker-compose.flaresolverr.yml up',
      error_file: path.join(LOG_DIR, 'flaresolverr-error.log'),
      out_file: path.join(LOG_DIR, 'flaresolverr-out.log'),
      merge_logs: true,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      ...PROCESS_POLICY,
    },
    {
      name: 'content-news',
      cwd: path.join(ROOT, 'content-production'),
      script: 'venv311/bin/uvicorn',
      args:
        'agencies:app --host 0.0.0.0 --port 8000 --workers 1 --limit-concurrency 1000 --timeout-keep-alive 30',
      interpreter: path.join(ROOT, 'content-production/venv311/bin/python'),
      env: {
        FLARESOLVERR_URL: 'http://127.0.0.1:8191/v1',
        CRAWL_PLAYWRIGHT_ENABLED: 'true',
        BACKEND_ADD_NEWS_URL:
          'http://127.0.0.1:4002/api/ai/rasad-khabar/add-news-title',
        BACKEND_ONBOARD_CALLBACK_URL:
          'http://127.0.0.1:4002/api/ai/rasad-khabar/onboard-callback',
        BACKEND_POLL_HEALTH_URL:
          'http://127.0.0.1:4002/api/ai/rasad-khabar/source-poll-health',
        CRAWL_CALLBACK_SECRET: process.env.CRAWL_CALLBACK_SECRET,
        CRAWL_POLL_INTERVAL_SEC: '90',
      },
      error_file: path.join(LOG_DIR, 'content-news-error.log'),
      out_file: path.join(LOG_DIR, 'content-news-out.log'),
      merge_logs: true,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      ...PROCESS_POLICY,
    },
    {
      name: 'source-onboarding-worker',
      cwd: path.join(ROOT, 'content-production'),
      script: 'onboarding_worker.py',
      interpreter: path.join(ROOT, 'content-production/venv311/bin/python'),
      env: {
        BACKEND_BASE_URL: 'http://127.0.0.1:4002',
        CRAWL_CALLBACK_SECRET: process.env.CRAWL_CALLBACK_SECRET,
        CRAWL_PLAYWRIGHT_ENABLED: 'true',
        FLARESOLVERR_URL: 'http://127.0.0.1:8191/v1',
        CRAWL_ONBOARD_WORKER_CONCURRENCY: '2',
        CRAWL_ONBOARD_WORKER_POLL_SEC: '2',
        CRAWL_ONBOARD_HEARTBEAT_SEC: '15',
        CRAWL_WORKER_COMPLETE_TIMEOUT_SEC: '120',
      },
      error_file: path.join(LOG_DIR, 'source-onboarding-worker-error.log'),
      out_file: path.join(LOG_DIR, 'source-onboarding-worker-out.log'),
      merge_logs: true,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      ...PROCESS_POLICY,
    },
    {
      name: 'content-translate',
      cwd: path.join(ROOT, 'content-production'),
      script: 'venv311/bin/uvicorn',
      args:
        'translate:app --host 0.0.0.0 --port 8001 --workers 1 --limit-concurrency 1000 --timeout-keep-alive 30',
      interpreter: path.join(ROOT, 'content-production/venv311/bin/python'),
      env: {
        FLARESOLVERR_URL: 'http://127.0.0.1:8191/v1',
        CRAWL_PLAYWRIGHT_ENABLED: 'true',
      },
      error_file: path.join(LOG_DIR, 'content-translate-error.log'),
      out_file: path.join(LOG_DIR, 'content-translate-out.log'),
      merge_logs: true,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      ...PROCESS_POLICY,
    },
    {
      name: 'auth-service',
      cwd: path.join(ROOT, 'authentication-and-authorization'),
      script: 'dist/main.js',
      env: {
        NODE_ENV: 'development',
        DISABLE_SMS: 'true',
        PASSWORD_RESET_VIA_EMAIL: 'true',
        FORGET_PASSWORD_MAX_PER_24H: '50',
      },
      error_file: path.join(LOG_DIR, 'auth-service-error.log'),
      out_file: path.join(LOG_DIR, 'auth-service-out.log'),
      merge_logs: true,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      ...PROCESS_POLICY,
    },
    {
      name: 'captcha-service',
      cwd: path.join(ROOT, 'captcha'),
      script: 'dist/main.js',
      env: {
        NODE_ENV: 'development',
      },
      error_file: path.join(LOG_DIR, 'captcha-service-error.log'),
      out_file: path.join(LOG_DIR, 'captcha-service-out.log'),
      merge_logs: true,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      ...PROCESS_POLICY,
    },
    {
      name: 'content-reflection',
      cwd: path.join(ROOT, 'content-production'),
      script: 'venv311/bin/uvicorn',
      args:
        'news_reflection:app --host 0.0.0.0 --port 8002 --workers 1 --limit-concurrency 100 --timeout-keep-alive 120',
      interpreter: path.join(ROOT, 'content-production/venv311/bin/python'),
      env: {
        FLARESOLVERR_URL: 'http://127.0.0.1:8191/v1',
        CRAWL_PLAYWRIGHT_ENABLED: 'true',
        REFLECTION_GROK_MODEL: 'grok-3-mini',
        REFLECTION_GROK_REASONING_EFFORT: 'low',
      },
      error_file: path.join(LOG_DIR, 'content-reflection-error.log'),
      out_file: path.join(LOG_DIR, 'content-reflection-out.log'),
      merge_logs: true,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      ...PROCESS_POLICY,
    },
  ],
};