const path = require('path');

const ROOT = __dirname;
const AUTH_ROOT = '/home/shahab/Desktop/auth-capcha/authentication-and-authorization';
const LOG_DIR = path.join(ROOT, 'logs');
const NODE20 = '/home/shahab/.nvm/versions/node/v20.20.2/bin/node';

module.exports = {
  apps: [
    {
      name: 'hoshmak-back',
      cwd: path.join(ROOT, 'hoshmak-back'),
      script: 'dist/main.js',
      interpreter: NODE20,
      env: {
        NODE_ENV: 'development',
      },
      error_file: path.join(LOG_DIR, 'hoshmak-back-error.log'),
      out_file: path.join(LOG_DIR, 'hoshmak-back-out.log'),
      merge_logs: true,
      autorestart: true,
      restart_delay: 3000,
      exp_backoff_restart_delay: 100,
      max_restarts: 15,
      min_uptime: '10s',
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      name: 'hoshmak-front',
      cwd: path.join(ROOT, 'hoshmak-front'),
      script: 'node_modules/.bin/vite',
      args: 'preview --host 0.0.0.0 --port 4000 --strictPort',
      interpreter: NODE20,
      env: {
        NODE_ENV: 'production',
      },
      error_file: path.join(LOG_DIR, 'hoshmak-front-error.log'),
      out_file: path.join(LOG_DIR, 'hoshmak-front-out.log'),
      merge_logs: true,
      autorestart: true,
      restart_delay: 3000,
      exp_backoff_restart_delay: 100,
      max_restarts: 15,
      min_uptime: '10s',
    },
    {
      name: 'ai-services',
      cwd: path.join(ROOT, 'ai-services'),
      script: 'dist/main.js',
      interpreter: NODE20,
      env: {
        NODE_ENV: 'development',
      },
      error_file: path.join(LOG_DIR, 'ai-services-error.log'),
      out_file: path.join(LOG_DIR, 'ai-services-out.log'),
      merge_logs: true,
      autorestart: true,
      restart_delay: 3000,
      exp_backoff_restart_delay: 100,
      max_restarts: 15,
      min_uptime: '10s',
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      name: 'content-news',
      cwd: path.join(ROOT, 'content-production'),
      script: 'venv311/bin/uvicorn',
      args:
        'agencies:app --host 0.0.0.0 --port 8000 --workers 1 --limit-concurrency 1000 --timeout-keep-alive 30',
      interpreter: path.join(ROOT, 'content-production/venv311/bin/python'),
      error_file: path.join(LOG_DIR, 'content-news-error.log'),
      out_file: path.join(LOG_DIR, 'content-news-out.log'),
      merge_logs: true,
      autorestart: true,
      restart_delay: 3000,
      exp_backoff_restart_delay: 100,
      max_restarts: 15,
      min_uptime: '10s',
    },
    {
      name: 'content-translate',
      cwd: path.join(ROOT, 'content-production'),
      script: 'venv311/bin/uvicorn',
      args:
        'translate:app --host 0.0.0.0 --port 8001 --workers 1 --limit-concurrency 1000 --timeout-keep-alive 30',
      interpreter: path.join(ROOT, 'content-production/venv311/bin/python'),
      error_file: path.join(LOG_DIR, 'content-translate-error.log'),
      out_file: path.join(LOG_DIR, 'content-translate-out.log'),
      merge_logs: true,
      autorestart: true,
      restart_delay: 3000,
      exp_backoff_restart_delay: 100,
      max_restarts: 15,
      min_uptime: '10s',
    },
    {
      name: 'content-reflection',
      cwd: path.join(ROOT, 'content-production'),
      script: 'venv311/bin/uvicorn',
      args:
        'news_reflection:app --host 0.0.0.0 --port 8002 --workers 1 --limit-concurrency 100 --timeout-keep-alive 120',
      interpreter: path.join(ROOT, 'content-production/venv311/bin/python'),
      error_file: path.join(LOG_DIR, 'content-reflection-error.log'),
      out_file: path.join(LOG_DIR, 'content-reflection-out.log'),
      merge_logs: true,
      autorestart: true,
      restart_delay: 3000,
      exp_backoff_restart_delay: 100,
      max_restarts: 15,
      min_uptime: '10s',
    },
    {
      name: 'auth-service',
      cwd: AUTH_ROOT,
      script: 'dist/main.js',
      interpreter: NODE20,
      env: {
        NODE_ENV: 'development',
        DISABLE_SMS: 'true',
        PASSWORD_RESET_VIA_EMAIL: 'true',
      },
      error_file: path.join(LOG_DIR, 'auth-service-error.log'),
      out_file: path.join(LOG_DIR, 'auth-service-out.log'),
      merge_logs: true,
      autorestart: true,
      restart_delay: 3000,
      exp_backoff_restart_delay: 100,
      max_restarts: 15,
      min_uptime: '10s',
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
  ],
};
